apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-mec-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-mec-app-1
  template:
    metadata:
      labels:
        app: oai-mec-app-1
      annotations:
        k8s.v1.cni.cncf.io/networks: oai-mec-app-1-nad
    spec:
      nodeSelector:
        kubernetes.io/hostname: [Edge Node Name]
      containers:
        - name: oai-mec-app-1
          image: ubuntu:20.04
          command:
            - /bin/bash
            - -c
            - |
              apt update && \
              apt install -y python3-pip vim net-tools curl && \
              pip install flask requests && \
              python3 /app/app.py
          volumeMounts:
          - name: script-volume
            mountPath: /app
          ports:
            - containerPort: 80
      volumes:
        - name: script-volume
          configMap:
            name: oai-mec-app-1-script
      restartPolicy: Always