apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
      annotations:
        k8s.v1.cni.cncf.io/networks: oai-mec-app-2-nad
    spec:
      nodeSelector:
        kubernetes.io/hostname: ns
      containers:
        - name: app-2
          image: corfr/tcpdump
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          command: ["/bin/sh", "-c", "sleep infinity"]
      restartPolicy: Always