apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: oai-mec-app-2-nad
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "enp0s3",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.0.2.107/24",
            "gateway": "10.0.2.2"
          }
        ]
      }
    }'