apiVersion: v1
kind: Service
metadata:
  name: upf-n3-service
  namespace: default
spec:
  selector:
    app: free5gc-upf
  ports:
    - protocol: UDP
      port: 2152
      targetPort: 2152
  type: NodePort