apiVersion: v1
kind: Service
metadata:
  name: oai-mep-gateway-service
spec:
  selector:
    app: oai-mep-gateway
  ports:
    - name: http
      port: 8002
      targetPort: 8002
    - name: admin
      port: 8001
      targetPort: 8001
