apiVersion: v1
kind: Service
metadata:
  name: openness-af-service
spec:
  selector:
    app: openness-af
  type: NodePort
  ports:
  - port: 8050
    targetPort: 8050
    nodePort: 30051
    protocol: TCP
    name: cnca
  - port: 8051
    targetPort: 8051
    nodePort: 30052
    protocol: TCP
    name: nef
  